# -*- coding: utf-8 -*-
"""data structure.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NiFZ8x_wxZPxrkR2GEqH8GHspidA86qv
"""

class SportsRegistration:
    def __init__(self):
        self.students = []

    def add_student(self, name):
        if name not in self.students:
            self.students.append(name)
            print(f"{name} added successfully.")
        else:
            print(f"{name} is already registered.")

    def remove_student(self, name):
        if name in self.students:
            self.students.remove(name)
            print(f"{name} removed.")
        else:
            print(f"{name} not found in the list.")

    def show_students(self):
        print("Registered Students:", self.students)


# --- Main Program ---
reg = SportsRegistration()

while True:
    action = input("Enter add/remove/q: ")

    if action == "add":
        name = input("Enter student name: ")
        reg.add_student(name)

    elif action == "remove":
        name = input("Enter student name: ")
        reg.remove_student(name)

    elif action == "q":
        reg.show_students()
        break

    else:
        print("Invalid option.")

class RestaurantHours:
    def __init__(self):
        self.timings = {
            "Monday": "9 AM - 10 PM",
            "Tuesday": "9 AM - 10 PM",
            "Wednesday": "9 AM - 10 PM",
            "Thursday": "9 AM - 10 PM",
            "Friday": "9 AM - 11 PM",
            "Saturday": "10 AM - 11 PM",
            "Sunday": "10 AM - 8 PM"
        }

    def get_time(self, day):
        day = day.capitalize()
        if day in self.timings:
            print(day, ":", self.timings[day])
        else:
            print("Invalid day entered.")


# --- Main Program ---
rest = RestaurantHours()

day = input("Enter a day: ")
rest.get_time(day)

class EventEntry:
    def __init__(self):
        self.entered_students = set()

    def enter(self, student_id):
        if student_id in self.entered_students:
            print("This student has already entered.")
        else:
            self.entered_students.add(student_id)
            print("Entry recorded.")

    def show_all(self):
        print("Students who entered:", self.entered_students)


# --- Main Program ---
event = EventEntry()

while True:
    sid = input("Enter student ID (or q to quit): ")

    if sid == "q":
        event.show_all()
        break

    event.enter(sid)

class BookCart:
    def __init__(self):
        self.books = {}  # book : price

    def add_book(self, name, price):
        self.books[name] = price
        print(f"{name} added/updated.")

    def show_bill(self):
        total = sum(self.books.values())
        print("Books and Prices:", self.books)
        print("Total Amount:", total)


# --- Main Program ---
cart = BookCart()

while True:
    cmd = input("Enter 'add' or 'q': ")

    if cmd == "add":
        name = input("Book name: ")
        price = int(input("Price: "))
        cart.add_book(name, price)

    elif cmd == "q":
        cart.show_bill()
        break

    else:
        print("Invalid input.")

class ShoppingCart:
    def __init__(self):
        self.items = []

    def add_item(self, item):
        self.items.append(item)
        print(f"{item} added.")

    def remove_item(self, item):
        if item in self.items:
            self.items.remove(item)
            print(f"{item} removed.")
        else:
            print("Item not found.")

    def show_items(self):
        print("Shopping List:", self.items)


# --- Main Program ---
cart = ShoppingCart()

while True:
    cmd = input("Enter add/remove/q: ")

    if cmd == "add":
        item = input("Enter item: ")
        cart.add_item(item)

    elif cmd == "remove":
        item = input("Enter item: ")
        cart.remove_item(item)

    elif cmd == "q":
        cart.show_items()
        break

    else:
        print("Invalid option.")





